server:
  port: 8080

spring:
  application:
    name: cine-mind
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

kofic:
  api:
    key: ${KOFIC_API_KEY}

kmdb:
  api:
    key: ${KMDB_API_KEY}

openai:
  api:
    key: ${OPENAI_API_KEY}
    # RAG 임베딩 API URL 추가 (text-embedding-3-small 모델 사용)
    embedding-url: "https://api.openai.com/v1/embeddings"
    # Chat Completion API URL 추가 (gpt-4o-mini 모델 사용)
    chat-url: "https://api.openai.com/v1/chat/completions"

rag:
  splitter:
    chunk-size: 300
    chunk-overlap: 50

logging:
  level:
    org.springframework.security: DEBUG