spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: never

jwt:
  secret:
    key: "abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd"

kofic:
  api:
    key: "test-kofic-api-key-test-kofic-api-key-test-kofic-api-key"

kmdb:
  api:
    key: "test-kmdb-api-key-test-kmdb-api-key-test-kmdb-api-key"

openai:
  api:
    key: "test-openai-api-key-test-openai-api-key-test-openai-api-key"



